import "./globals.css";
import Providers from "./Providers";
import type { Metadata } from "next";
import Navbarr from "../components/navbar/Navbarr";

export const metadata: Metadata = {
  title: "Counter Top",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className='sticky top-0 z-40 bg-grey-800'>
          <div className="flex h-11 px-4 sm:px-0 max-w-[980px] mx-auto">
            <Navbarr />
          </div>
        </div>
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}
