import type { Metadata } from "next";
// import { Inter } from "next/font/google";
import "./globals.css";
import Navbarr from "../components/navbar/Navbarr";
import Providers from "./Providers";

// const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className='bg-grey w-full px-4'>
          <Navbarr />
        </div>
        <Providers>
          <div className='px-4'>
            {children}
          </div>
        </Providers>
      </body>
    </html>
  );
}
